RecipeViewer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('viewer.urls')),
    path('admin/', admin.site.urls),
]

viewer/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<int:recipe_id>', views.recipe, name='recipe'),
    path('add-recipe/', views.addRecipe, name='add-recipe'),
    path('add-recipe-manual/', views.addRecipeManual, name='add-recipe'),
    path('add-recipe/failed', views.failedAdd, name='add-recipe-failed'),
    path('add-recipe/success', views.successAdd, name='add-recipe-success'),
    path('search', views.search, name='search'),
    path('export', views.export, name='export'),
]

viewer/models.py
from django.db import models
from django.forms import ModelForm

# Defines a recipe data model
# based on https://schema.org/Recipe
class Recipe(models.Model):
    def __str__(self):
        return self.name
    
     # From Thing schema
     # https://schema.org/Thing
    webAddress = models.URLField()
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    image = models.TextField(blank=True, null=True)

     # From Creative Work schema
     # https://schema.org/CreativeWork
    author = models.TextField()
    datePublished = models.DateField(blank=True, null=True)
    publisher = models.TextField(blank=True, null=True)

     # From How To schema
     # https://schema.org/HowTo
    estimatedCost = models.DecimalField(max_digits = 5, decimal_places = 2, blank=True, null=True)
    prepTime = models.DurationField(blank=True, null=True)
    totalTime = models.DurationField(blank=True, null=True)

     # From Recipe schema
    cookTime = models.DurationField(blank=True, null=True)
    cookingMethod = models.TextField(blank=True, null=True)
    recipeCategory = models.TextField(blank=True, null=True)
    recipeCuisine = models.TextField(blank=True, null=True)
    recipeIngredient = models.TextField() # may cause issues later, have to check
    recipeInstructions = models.TextField()
    suitableForDiet = models.TextField(blank=True, null=True) # need to process enums for storage

    # Non-schema - added for app functionality
    dateSaved = models.DateTimeField()

# Form for manual entry of Recipe data
class AddRecipeManual(ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'
        

# Describes a recipe's nutritional information
# based on https://schema.org/NutritionInformation
class NutritionalInfo(models.Model):
    def __str__(self):
        return self.recipe.name + " nutritional info"

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    calories = models.TextField(blank=True, null=True)
    carbohydrateContent = models.TextField(blank=True, null=True)
    cholesterolContent = models.TextField(blank=True, null=True)
    fatContent = models.TextField(blank=True, null=True)
    fiberContent = models.TextField(blank=True, null=True)
    proteinContent = models.TextField(blank=True, null=True)
    saturatedFatContent = models.TextField(blank=True, null=True)
    servingSize = models.TextField(blank=True, null=True)
    sodiumContent = models.TextField(blank=True, null=True)
    sugarContent = models.TextField(blank=True, null=True)
    transFatContent = models.TextField(blank=True, null=True)
    unsaturatedFatContent = models.TextField(blank=True, null=True)

# Keywords map keyword -> Recipe
# Used to improve recipe searching
class Keyword(models.Model):
    def __str__(self):
        return self.keyword + " | " + self.recipe.name

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    keyword = models.TextField()

viewer/forms.py
from django import forms

class AddRecipeForm(forms.Form):
    url = forms.URLField(label="URL")

class SearchForm(forms.Form):
    searchTerm = forms.CharField(label="", label_suffix="")

viewer/views.py
import viewer
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.utils import timezone
from django.db.models import Q
from datetime import date
from dateutil.parser import parse
from django.core.serializers import serialize
import json

from scrape_schema_recipe import scrape_url

from .models import Recipe, NutritionalInfo, Keyword, AddRecipeManual
from .forms import AddRecipeForm, SearchForm

# App homepage
def index(request):
    context = {}
    return render(request, 'viewer/index.html', context)

# Displays a stored recipe to the user
# Takes an integer recipe ID to select which recipe to display
def recipe(request, recipe_id):
    recipe = Recipe.objects.filter(id = recipe_id).first()

    if recipe.estimatedCost == None:
        estimatedCost = "Unknown"
    else:
        estimatedCost = recipe.estimatedCost

    ingredients_list = "<ul id='ingredients-list'>"
    for ingredient in json.loads(recipe.recipeIngredient):
        ingredients_list += "<li>" + ingredient + "</li>"
    ingredients_list += "</ul>"

    if recipe.cookTime == None:
        cookTime = "Unspecified"
    else:
        cookTime = recipe.cookTime
    if recipe.prepTime == None:
        prepTime = "Unspecified"
    else:
        prepTime = recipe.prepTime
    if recipe.totalTime == None:
        totalTime = "Unspecified"
    else:
        totalTime = recipe.totalTime

    context = {
        'name' : recipe.name,
        'image_url' : recipe.image, 
        'description' : recipe.description,
        'ingredients_list' : ingredients_list,
        'instructions_list' : recipe.recipeInstructions,
        'recipe_category' : recipe.recipeCategory,
        'recipe_cuisine' : recipe.recipeCuisine,
        'diet_type' : recipe.suitableForDiet,
        'estimated_cost' : estimatedCost,
        'author' : recipe.author,
        'publisher' : recipe.publisher,
        'date_published' : recipe.datePublished,
        'cook_time' : cookTime,
        'prep_time' : prepTime,
        'total_time' : totalTime,

        'date_saved' : recipe.dateSaved.strftime("%A %d %B %Y %X"),
        'url' : recipe.webAddress
    }

    if NutritionalInfo.objects.filter(recipe_id = recipe_id).count() > 0:
        nutritionalInfo = NutritionalInfo.objects.filter(recipe_id = recipe_id).first()

        context['calories'] = nutritionalInfo.calories
        context['carbohydrates'] = nutritionalInfo.carbohydrateContent
        context['sugar'] = nutritionalInfo.sugarContent
        context['cholesterol'] = nutritionalInfo.cholesterolContent
        context['fat'] = nutritionalInfo.fatContent
        context['fat_saturated'] = nutritionalInfo.saturatedFatContent
        context['fat_unsaturated'] = nutritionalInfo.unsaturatedFatContent
        context['fat_trans'] = nutritionalInfo.transFatContent
        context['fibre'] = nutritionalInfo.fiberContent
        context['protein'] = nutritionalInfo.proteinContent
        context['sodium'] = nutritionalInfo.sodiumContent
        context['serving_size'] = nutritionalInfo.servingSize

        return render(request, 'viewer/viewRecipeNutrition.html', context)
    else:
        return render(request, 'viewer/viewRecipe.html', context)

# Allows users to add recipes via a URL to a page containing a recipe Schema
def addRecipe(request):
    
    if request.method == 'POST':
        form = AddRecipeForm(request.POST)
        
        if form.is_valid():
            url = form.cleaned_data['url']
            print("URL Recieved: " + url)

            recipe_list = scrape_url(url, python_objects=True)

            # Warning: The following code has a painful number of if/else statements. I kinda hate it tbh.
            # Unfortunately different sites have a habit of leaving out different schema sections. 
            # Hopefully I'll think of a better way of doing this in the future.
            if len(recipe_list) > 0:
                recipe = recipe_list[0]
                
                 # From Thing schema
                webAddress = recipe['url']
                name = recipe['name']
                description = recipe['description']

                if 'url' in recipe['image']:
                    image = recipe['image']['url']
                else:
                    image = recipe['image'][0]
                
                 # From Creative Work schema
                if isinstance(recipe['author'], list):
                    if 'name' in recipe['author'][0]:
                        author = recipe['author'][0]['name']
                    
                    else:
                        author = recipe['author'][0]
                else:
                    if isinstance(recipe['author'], str):
                        author = recipe['author']
                    elif 'name' in recipe['author']:
                        author = recipe['author']['name']
                    else:
                        author = 'UNKNOWN'
                if 'datePublished' in recipe:
                    if isinstance(recipe['datePublished'], str):
                        datePublished = parse(recipe['datePublished'])
                    elif isinstance(recipe['datePublished'], date):
                        datePublished = recipe['datePublished']
                    else:
                        datePublished = recipe['datePublished'].date()
                else:
                    datePublished = None
                if 'publisher' in recipe:
                    if 'name' in recipe['publisher']:
                        publisher = recipe['publisher']['name']
                    else:
                        publisher = recipe['publisher']
                else:
                    publisher = None

                 # From How To schema
                if 'estimatedCost' in recipe:
                    estimatedCost = recipe['estimatedCost']
                else:
                    estimatedCost = None
                if 'prepTime' in recipe:
                    prepTime = recipe['prepTime']
                else:
                    prepTime = None
                if 'totalTime' in recipe:
                    totalTime = recipe['totalTime']
                else:
                    totalTime = None


                 # From Recipe schema
                if 'cookTime' in recipe:
                    cookTime = recipe['cookTime']
                else:
                    cookTime = None

                if 'cookingMethod' in recipe:
                    cookingMethod = recipe['cookingMethod']
                else:
                    cookingMethod = None

                if 'nutrition' in recipe:
                    nutrition = recipe['nutrition']
                else:
                    nutrition = None

                if 'recipeCategory' in recipe:
                    recipeCategory = recipe['recipeCategory']
                else:
                    recipeCategory = None

                if 'recipeCuisine' in recipe:
                    recipeCuisine = recipe['recipeCuisine']
                else:
                    recipeCuisine = None

                recipeIngredient = json.dumps(recipe['recipeIngredient'])

                if isinstance(recipe['recipeInstructions'], list):
                    if '@type' in recipe['recipeInstructions'][0]:
                        if recipe['recipeInstructions'][0]['@type'] == 'HowToSection':
                            instructionList = recipe['recipeInstructions'][0]['itemListElement']
                        elif recipe['recipeInstructions'][0]['@type'] == 'HowToStep':
                            instructionList = list()
                            for step in recipe['recipeInstructions']:
                                if step['@type'] == 'HowToStep':
                                    instructionList.append(step)
                        else:
                            instructionList = recipe['recipeInstructions']
                        outputText = "<ol id='instructions-list'>"
                        for x in range(0, len(instructionList)):
                            currentStep = x
                            outputText += "<li>" + instructionList[x]['text'] + "</li>"
                        outputText += "</ol>"
                        recipeInstructions = outputText
                    elif len(recipe['recipeInstructions']) > 1:
                        outputText = "<ol id='instructions-list'>"
                        for howToStep in recipe['recipeInstructions']:
                            outputText += "<li>" + howToStep + "</li>"
                        outputText += "</ol>"
                        recipeInstructions = outputText
                    else:
                        recipeInstructions = "<p>" + recipe['recipeInstructions'][0] + "</p>"
                else:
                    recipeInstructions = recipe['recipeInstructions']

                if 'suitableForDiet' in recipe:
                    suitableForDiet = recipe['suitableForDiet']
                else:
                    suitableForDiet = None

                dateSaved = timezone.now()


                # Saves creates new recipe object in DB
                r = Recipe(
                    webAddress = webAddress,
                    name = name,
                    description = description,
                    image = image,
                    author = author,
                    datePublished = datePublished,
                    publisher = publisher,
                    estimatedCost = estimatedCost,
                    prepTime = prepTime,
                    totalTime = totalTime,
                    cookTime = cookTime,
                    cookingMethod = cookingMethod,
                    recipeCategory = recipeCategory,
                    recipeCuisine = recipeCuisine,
                    recipeIngredient = recipeIngredient,
                    recipeInstructions = recipeInstructions,

viewer/templates/viewer/addRecipe.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Add Recipe - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Add recipe</h1>
            <div class="add-recipe-form">
                <p>Submit a recipe's URL to save it to the database.</p>
                <form method="post" class="url-form">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="search-button">Submit</button>
                </form>
            </div>
        </div>
    </body>
</html>

viewer/templates/viewer/addRecipeManual.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Add Recipe - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Add recipe</h1>
            <div class="add-recipe-form">
                <p>Submit a recipe's data to save it to the database.</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="input_block" style="display:inline-block;">
                    <div>
                        <label for="id_webAddress">Web Address:</label>
                        {{ manual_recipe_form.webAddress.errors }}
                        {{ manual_recipe_form.webAddress }}
                    </div>
                    <div>
                        <label for="id_name">Recipe Name:</label>
                        {{ manual_recipe_form.name.errors }}
                        {{ manual_recipe_form.name }}
                    </div>
                    <div>
                        <label for="id_description">Description:</label>
                        {{ manual_recipe_form.description.errors }}
                        {{ manual_recipe_form.description }}
                    </div>
                    <div>
                        <label for="id_image">Image Address:</label>
                        {{ manual_recipe_form.image.errors }}
                        {{ manual_recipe_form.image }}
                    </div>
                    <div>
                        <label for="id_author">Author:</label>
                        {{ manual_recipe_form.author.errors }}
                        {{ manual_recipe_form.author }}
                    </div>
                    <div>
                        <label for="id_datePublished">Date Published:</label>
                        {{ manual_recipe_form.datePublished.errors }}
                        {{ manual_recipe_form.datePublished }}
                    </div>
                    <div>
                        <label for="id_published">Publisher:</label>
                        {{ manual_recipe_form.publisher.errors }}
                        {{ manual_recipe_form.publisher }}
                    </div>
                    <div>
                        <label for="id_estimatedCost">Estimated Cost:</label>
                        {{ manual_recipe_form.estimatedCost.errors }}
                        {{ manual_recipe_form.estimatedCost }}
                    </div>
                    <div>
                        <label for="id_prepTime">Prep Time:</label>
                        {{ manual_recipe_form.prepTime.errors }}
                        {{ manual_recipe_form.prepTime }}
                    </div>
                    <div>
                        <label for="id_totalTime">Total Time:</label>
                        {{ manual_recipe_form.totalTime.errors }}
                        {{ manual_recipe_form.totalTime }}
                    </div>
                    <div>
                        <label for="id_cookTime">Cook Time:</label>
                        {{ manual_recipe_form.cookTime.errors }}
                        {{ manual_recipe_form.cookTime }}
                    </div>
                    <div>
                        <label for="id_cookMethod">Cooking Method:</label>
                        {{ manual_recipe_form.cookMethod.errors }}
                        {{ manual_recipe_form.cookMethod }}
                    </div>
                    <div>
                        <label for="id_recipeCategory">Category:</label>
                        {{ manual_recipe_form.recipeCategory.errors }}
                        {{ manual_recipe_form.recipeCategory }}
                    </div>
                    <div>
                        <label for="id_recipeCuisine">Cuisine:</label>
                        {{ manual_recipe_form.recipeCuisine.errors }}
                        {{ manual_recipe_form.recipeCuisine }}
                    </div>
                    <div>
                        <label for="id_recipeIngredient">Ingredients:</label>
                        {{ manual_recipe_form.recipeIngredient.errors }}
                        {{ manual_recipe_form.recipeIngredient }}
                    </div>
                    <div>
                        <label for="id_recipeInstructions">Instructions:</label>
                        {{ manual_recipe_form.recipeInstructions.errors }}
                        {{ manual_recipe_form.recipeInstructions }}
                    </div>
                    <div>
                        <label for="id_suitableForDiet">Diet Types:</label>
                        {{ manual_recipe_form.suitableForDiet.errors }}
                        {{ manual_recipe_form.suitableForDiet }}
                    </div>
                    <div>
                        <label for="id_dateSaved">Date Saved:</label>
                        {{ manual_recipe_form.dateSaved.errors }}
                        {{ manual_recipe_form.dateSaved }}
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>

viewer/templates/viewer/failedAdd.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Failed Add - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Failed to add recipe</h1>

            <a href="../" class="menu-button">
                <div class="button">
                    <h2>Home</h2>
                </div>
            </a>
            <a href="../search" class="menu-button">
                <div class="button">
                    <h2>Search Recipes</h2>
                </div>
            </a>
            <a href="./" class="menu-button">
                <div class="button">
                    <h2>Back</h2>
                </div>
            </a>

        </div>
    </body>
</html>

viewer/templates/viewer/index.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Home - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Welcome to RecipeViewer</h1>
            <a href="add-recipe" class="menu-button">
                <div class="button">
                    <h2>Add Recipe</h2>
                </div>
            </a>
            <a href="search" class="menu-button">
                <div class="button">
                    <h2>Search Recipes</h2>
                </div>
            </a>
        </div>
    </body>
</html>

viewer/templates/viewer/search.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Search - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Search Recipes:</h1>
            
            <div class="search-form">
                <form method="post">
                    {% csrf_token %}
                    {{ searchForm }}
                    {% comment %} <input type="text" name="searchTerm" required=""> {% endcomment %}
                    <button type="submit" class="search-button">Search</button>
                </form>
            </div>

            <div class="break"></div>

            <a href="add-recipe" class="menu-button">
                <div class="button">
                    <h2>Add Recipe</h2>
                </div>
            </a>
            <a href="./" class="menu-button">
                <div class="button">
                    <h2>Home</h2>
                </div>
            </a>
        </div>
    </body>
</html>

viewer/templates/viewer/searchResults.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Search - RecipeViewer</title>
    </head>
    <body>
        <div class="container" style="padding-top:1em;">
            <h1 class="heading-text">Search Recipes:</h1>
            
            <div class="search-form">
                <form method="post">
                    {% csrf_token %}
                    {{ searchForm }}
                    {% comment %} <input type="text" name="searchTerm" required=""> {% endcomment %}
                    <button type="submit" class="search-button">Search</button>
                </form>
            </div>

            <div class="break"></div>

            <div class="search-results">
                {{ search_results | safe}}
            </div>

            <div class="break"></div>

            <a href="add-recipe" class="menu-button">
                <div class="button">
                    <h2>Add Recipe</h2>
                </div>
            </a>
            <a href="./" class="menu-button">
                <div class="button">
                    <h2>Home</h2>
                </div>
            </a>
        </div>
    </body>
</html>

viewer/templates/viewer/successAdd.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>Successful Add - RecipeViewer</title>
    </head>
    <body>
        <div class="container">
            <h1 class="heading-text">Recipe Added</h1>

            <a href="../" class="menu-button">
                <div class="button">
                    <h2>Home</h2>
                </div>
            </a>
            <a href="../search" class="menu-button">
                <div class="button">
                    <h2>Search Recipes</h2>
                </div>
            </a>
            <a href="./" class="menu-button">
                <div class="button">
                    <h2>Back</h2>
                </div>
            </a>

        </div>
    </body>
</html>

viewer/templates/viewer/viewRecipe.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'viewer/recipe-style.css' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'viewer/img/favicon.ico' %}">
        <title>{{ name }} - RecipeViewer</title>
    </head>
    <body>
        <div class="recipe">
            <h1 id="recipe-title">{{ name }}</h1>
            <div id="description-block">
                <img class="recipe-image" src="{{ image_url }}" alt="Recipe Image">
                <p id="recipe-description">{{ description }}</p>
            </div>

            <div id="recipe-info">
                <p id="recipe-category">Category: {{ recipe_category }}</p>
                <p id="recipe-cuisine">Cuisine: {{ recipe_cuisine }}</p>
                <p id="recipe-diet">Diet Type: {{ diet_type }}</p>
                <p id="recipe-cost">Estimated Cost: {{ estimated_cost }}
            </div>

            <div id="publisher-info">
                <p id="author">Author: {{ author }}</p>
                <p id="publisher">Publisher: {{ publisher }}</p>
                <p id="date-published">Date Published: {{date_published}}</p>
            </div>

            <div class="break"></div>

            <div id="timing-info">
                <p id="cook-time">Cooking Time: {{ cook_time }}</p>
                <p id="prep-time">Prep Time: {{ prep_time }}</p>
                <p id="total-time">Total Time: {{ total_time }}</p>
            </div>

            {% comment %} 
                This could potentially create problems if the user cooks recipes made of '</li></ul><script>...' 
                I'm gonna rely on people not cooking delicious script injections for now.
            {% endcomment %}
            <div id="ingredients-block">
                <h2>Ingredients</h2>
                {{ ingredients_list | safe }}
            </div>
            <div id="instructions-block">
                <h2>Method</h2>
                {{ instructions_list | safe }}
            </div>

            <div id="footer">
                <p id="date-saved">Recipe saved on {{ date_saved }}</p>
                <p id="url">Original URL: <a href="{{ url }}">{{ url }}</a></p>
            </div>
        </div>

        

    </body>
</html>